pin cryptography and use ecosystem tests cli

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,7 +28,7 @@ executors:
     machine:
       image: ubuntu-1604:201903-01
 
-  cloudify-machine-510:
+  cloudify-machine-py3:
     machine:
       image: ubuntu-1604:201903-01
 
@@ -199,17 +199,17 @@ commands:
           paths:
             - build/*
 
-  run_integration_tests_505:
+  create_manager_container_505:
     steps:
       - run:
           name: "Pull Submodules"
           command: |
-            git submodule update --init --recursive
+            git submodule update --init --recursive --remote
       - attach_workspace:
           at: workspace
       - run:
           name: update pip
-          command: pip install -U pip
+          command: pip install -U pip===20.3.3
       - run:
           name: install cloudify
           command: |
@@ -231,10 +231,9 @@ commands:
           command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host cloudifyplatform/premium-cloudify-manager-aio
       - run:
           name: install local project
-          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
-      - run: pytest -s .circleci/test_examples.py
+          command:  pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
 
-  run_integration_tests_510:
+  create_manager_container_py3:
     steps:
       - run:
           name: "Pull Submodules"
@@ -244,30 +243,34 @@ commands:
           at: workspace
       - run:
           name: update pip
-          command: pip install -U pip
+          command: pip install -U pip===20.3.3
       - run:
           name: install cloudify
           command: |
             pip install -r test-requirements.txt
       - run:
           name: download manager docker image
-          command:  wget http://repository.cloudifysource.org/cloudify/5.1.0/.dev1-release/cloudify-manager-aio-docker-5.1.0.dev1.tar
-      - run:
-          name: load docker image
-          command: docker load -i cloudify-manager-aio-docker-5.1.0.dev1.tar
-      - run:
-          name: retain space by dumping the tar
-          command: rm cloudify-manager-aio-docker-5.1.0.dev1.tar
+          command:  docker pull cloudifyplatform/premium-cloudify-manager-aio:latest
       - run:
           name: show images
           command: docker images
       - run:
           name: start docker container
-          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host cloudify-manager-aio:latest
+          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host cloudifyplatform/premium-cloudify-manager-aio
+      - run:
+          name: wait for starter
+          command: docker exec -it cfy_manager cfy_manager wait-for-starter
       - run:
           name: install local project
           command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
-      - run: pytest -s .circleci/test_examples.py
+
+  prepare_test_manager:
+    steps:
+      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -es gcp_credentials=$gcp_credentials --bundle-path workspace/build/cloudify-plugins-bundle.tgz --yum-package python-netaddr --yum-package git
+
+  run_hello_world_test:
+    steps:
+      - run: ecosystem-test local-blueprint-test -b examples/blueprint-examples/hello-world-example/gcp.yaml --test-id=hello-world-example -i network_name=ansnet-$CIRCLE_BUILD_NUM -i subnet_name=anssub-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=1800
 
   release_plugin:
     steps:
@@ -277,11 +280,24 @@ commands:
             git submodule init
             git submodule update --remote --recursive
       - run:
+          name: Set Python
+          command: |
+            if ! pyenv -v COMMAND &> /dev/null
+            then
+                echo "pyenv could not be found"
+                exit
+            else
+                pyenv global 3.6.5
+            fi
+      - run:
           name: Download pip
           command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
       - run:
           name: Install pip
           command: sudo python get-pip.py
+      - run:
+          name: update pip
+          command: pip install -U pip===20.3.3
       - run:
           name: Install virtualenv
           command: pip install --user virtualenv
@@ -301,7 +317,6 @@ commands:
           at: workspace
       - run: python .circleci/package_release.py
 
-
   merge_docs:
     steps:
       - attach_workspace:
@@ -311,6 +326,16 @@ commands:
           command: |
             git submodule init
             git submodule update --remote --recursive
+      - run:
+          name: Set Python
+          command: |
+            if ! pyenv -v COMMAND &> /dev/null
+            then
+                echo "pyenv could not be found"
+                exit
+            else
+                pyenv global 3.6.5
+            fi
       - run:
           name: Download pip
           command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
@@ -351,19 +376,19 @@ jobs:
       - run_unittest
 
   py3_compat:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - check_py3_compat
 
   validate_version:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - validate_version
 
   validate_documentation:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - validate_documentation
@@ -381,7 +406,7 @@ jobs:
       - generate_rhel_py27py36_wagon
 
   build_bundle:
-    executor: wagon_generator
+    executor: py36
     steps:
       - checkout
       - build_archive
@@ -390,27 +415,30 @@ jobs:
     executor: cloudify-machine
     environment:
       CLOUDIFY_SSL_TRUST_ALL: true
-      IAAS: gcp
     steps:
       - checkout
-      - run_integration_tests_505
+      - create_manager_container_505
+      - prepare_test_manager
+      - run_hello_world_test
 
-  integration_tests_510:
-    executor: cloudify-machine-510
+  integration_tests_py3:
+    executor: cloudify-machine-py3
     environment:
       CLOUDIFY_SSL_TRUST_ALL: true
-      IAAS: gcp
     steps:
       - checkout
-      - run_integration_tests_510
+      - create_manager_container_py3
+      - prepare_test_manager
+      - run_hello_world_test
+
   release:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - release_plugin
 
   merge_docs:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - merge_docs
@@ -427,7 +455,8 @@ workflows:
       - wagon:
           filters:
             branches:
-              only: /([0-9\.]*\-build|master|dev)/
+#              only: /([0-9\.]*\-build|master|dev)/
+              only: /RD-1498-use-ecosystem-tests-cli/
       - rhel_wagon:
           filters:
             branches:
@@ -435,7 +464,8 @@ workflows:
       - build_bundle:
           filters:
             branches:
-              only: /master/
+#              only: /master/
+              only: /RD-1498-use-ecosystem-tests-cli/
           requires:
             - wagon
             - rhel_wagon
@@ -444,13 +474,15 @@ workflows:
             - build_bundle
           filters:
             branches:
-              only: /([0-9\.]*\-build|master|dev)/
-      - integration_tests_510:
+#              only: /([0-9\.]*\-build|master|dev)/
+              only: /RD-1498-use-ecosystem-tests-cli/
+      - integration_tests_py3:
           requires:
             - build_bundle
           filters:
             branches:
-              only: /([0-9\.]*\-build|master|dev)/
+#              only: /([0-9\.]*\-build|master|dev)/
+              only: /RD-1498-use-ecosystem-tests-cli/
       - release:
           filters:
             branches:
@@ -459,14 +491,14 @@ workflows:
             - validate_version
             - validate_documentation
             - integration_tests_505
-            - integration_tests_510
-      - merge_docs:
-          filters:
-            branches:
-              only: /master/
-          requires:
-            - release
-            - validate_documentation
+            - integration_tests_py3
+#      - merge_docs:
+#          filters:
+#            branches:
+#              only: /master/
+#          requires:
+#            - release
+#            - validate_documentation
   nightly:
     triggers:
     - schedule:
@@ -488,17 +520,22 @@ workflows:
           filters:
             branches:
               only: /([0-9\.]*\-build|master)/
-      - integration_tests_505:
+      - build_bundle:
+          filters:
+            branches:
+              only: /master/
           requires:
             - wagon
             - rhel_wagon
+      - integration_tests_505:
+          requires:
+            - build_bundle
           filters:
             branches:
               only: /([0-9\.]*\-build|master)/
-      - integration_tests_510:
+      - integration_tests_py3:
           requires:
-            - wagon
-            - rhel_wagon
+            - build_bundle
           filters:
             branches:
               only: /([0-9\.]*\-build|master)/
